---
title: "Proyecto 2 (Modelo AQI)"
author: "Monica Vargas Vallejo"
date: "`r Sys.Date()`"
output: html_document
---




#Library
```{r message=FALSE, warning=FALSE,echo=FALSE}
# Cargar librerías necesarias

ipak <- function(pkg){
  new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
  if (length(new.pkg)) 
    install.packages(new.pkg, dependencies = TRUE)
  sapply(pkg, require, character.only = TRUE)
}
packages <- c("readxl","tidyverse","GGally","dplyr","reticulate")
ipak(packages)


```


#Read Files
```{r message=FALSE, warning=FALSE,echo=FALSE}
data <- read.csv('data.csv')

#General inspection (unicamente un formalismo)
head(data)
dim(data)
str(data)
summary(data)
colSums(is.na(data))

normalize_zscore <- function(x) {
  return((x - mean(x, na.rm = TRUE)) / sd(x, na.rm = TRUE))
}



test <- data %>% sample_n(1000)

test_standardized <- test %>%
  mutate(across(c(NO2, PM10, SO2, CO, O3, AQI), normalize_zscore))

#distribution analysis 
test_standardized %>%
  pivot_longer(cols = c(NO2, PM10, SO2, CO, O3, AQI), names_to = "Variable", values_to = "Valor") %>%
  ggplot(aes(x = Valor, fill = Variable)) +
  geom_density(alpha = 0.5) +
  facet_wrap(~Variable, scales = "free") +
  theme_minimal()

#Variable Relation 

ggpairs(test_standardized, columns = c("NO2", "PM10", "SO2", "CO", "O3", "AQI"), aes(alpha = 0.5))
corr_matrix <- cor(test_standardized %>% select(NO2, PM10, SO2, CO, O3, AQI))
corrplot::corrplot(corr_matrix, method = "color", type = "lower", tl.col = "black", addCoef.col = "black")



#identificar atipicos 
test_standardized %>%
  pivot_longer(cols = c(NO2, PM10, SO2, CO, O3), names_to = "Variable", values_to = "Valor") %>%
  ggplot(aes(x = Variable, y = Valor)) +
  geom_boxplot(fill = "lightblue") +
  theme_minimal()

outliers <- test_standardized %>%
  summarise(across(everything(), 
                   ~{
                     Q1 <- quantile(.x, 0.25, na.rm = TRUE)
                     Q3 <- quantile(.x, 0.75, na.rm = TRUE)
                     IQR <- Q3 - Q1
                     Lower_Bound <- Q1 - 1.5 * IQR
                     Upper_Bound <- Q3 + 1.5 * IQR
                     sum(.x < Lower_Bound | .x > Upper_Bound, na.rm = TRUE)
                   }, 
                   .names = "Outliers_{.col}"))
print(outliers)


```


```{python}
import sys

sys.path.append("C:\\Users\\JUAN\\Desktop\\Algebra-lineal\\Proyecto 1 (K-means)\\repositorio\\Proyecto 2")
import codes as cd
import pandas as pd

data = pd.read_csv("data.csv")
data = data.values 

a=cd.quitar_ultima_columna(data)
b=cd.result_vector(data)

err,beta,grado=cd.pseudo_training(a,b)
print("error: ", err, " beta " , beta , " grado " , grado)

b = b.reshape(-1, 1)

err,beta,grado,iteration=cd.gradiente_training(a,b)
print("error",err,"beta",beta,"grado",grado,"iteracion",iteration)
```










